services:
  user-service:
    image: igladkikh/user-service:1.0
    container_name: user-service
    build: user-service/
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
      user-service-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071

  config-server:
    image: igladkikh/user-subscription-config-server:1.0
    container_name: user-subscription-config-server
    build: config-server/
    ports:
      - "8071:8071"

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_USER_SERVICE_DB}
      POSTGRES_USER: ${POSTGRES_USER_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_SERVICE_PASSWORD}
    ports:
      - "5430:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_USER_SERVICE_DB -U $$POSTGRES_USER_SERVICE_USER
      timeout: 5s
      interval: 5s
      retries: 10

  subscription-service-db:
    image: postgres:16.1
    container_name: subscription-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_SUBSCRIPTION_SERVICE_DB}
      POSTGRES_USER: ${POSTGRES_SUBSCRIPTION_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUBSCRIPTION_SERVICE_PASSWORD}
    ports:
      - "5431:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_SUBSCRIPTION_SERVICE_DB -U $$POSTGRES_SUBSCRIPTION_SERVICE_USER
      timeout: 5s
      interval: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: user-subscription-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server --include /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5