CREATE TABLE subscriptions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    expiry_date  DATE         NOT NULL,
    user_id      BIGINT REFERENCES users (id)
);